### ISSUE TITLE
No way to show an example value from an enum that is both valid and displays correctly in Apiary

### ISSUE THREAD

**Issue by anentropic** [apiaryio/mson#97]
We are trying to use an enum for querystring params like:

```apib
+ Parameters
    + country: `uk` (enum[string], optional) - Blah blah
        + Members
            + `**`
            + `uk`
            + `it`
            + `usa`
            + `oz`
```

In other words, define an enum _and_ show an example value from that enum when rendered in Apiary.

The construction above renders how we want in Apiary, but it causes a `duplicit value in enumeration` validation error.

I have tried other constructions but they each have a different issue in rendering:
```apib
+ Parameters
    + country (enum[string], optional) - Blah blah
        + Members
            + `**`
            + `uk`
            + `it`
            + `usa`
            + `oz`
```
...does not render an example like `country=uk` (renders as `country=`, as you would expect) but _does_ render the members of the enum as "possible values" and is valid.

```apib
+ Parameters
    + country: `uk` (CountryEnum, optional) - Blah blah

...

## CountryEnum (enum[string])
- `**`
- `uk`
- `it`
- `usa`
- `oz`
```
...no error about 'duplicit values' and renders the example value like we want, but _does not_ render the "possible values" from the enum 😞 

I think the inconsistent behaviour between enum defined in Data Structures and enum defined inline is a bug.

In my opinion:

- when enum is defined inline the parser should _not_ try to combine the example value with the `Members`... if you specify `Members` that should be the definition of the enum, and the example is just an example from the members.
- when the enum is defined in Data Structures it would still be useful to see the "possible values" rendered out

**Comment by anentropic** [comment]
Oh I forgot the other detail...

If we do this:

```apib
+ Parameters
    + country: `uk` (enum[string], optional) - Blah blah
        + Members
            + `**`
            + `it`
            + `usa`
            + `oz`
```

This is now a different validation error:

```
the example value 'uk' of parameter 'edition' is not in its list of expected values
```

These two validation errors can't both be right - either the example is counted as one of the members and added to the enum, or it is just an example and the enum is fully defined by `Members`.

I believe this supports the idea that there is a bug in the parser.

**Comment by anentropic** [comment]
FWIW there is a form which is both valid and renders as desired:
```apib
+ Parameters
    + country (enum[string], optional) - Blah blah
        + Sample: `uk`
        + Members
            + `**`
            + `uk`
            + `it`
            + `usa`
            + `oz`
```

this does not change the fact that the warnings detailed above suggest an inconsistency in the parser

**Comment by kylef** [comment]
Just want to mention, URI Parameters are not MSON. Parameters predate MSON quite a bit so some of the rules from MSON do not apply. We do have plans to make URI Parameters MSON in the future though.

Since it is not MSON, you cannot reference MSON types which is why some of your examples do not work. URI Parameters don't really have a type-system and the types (excluding enum) are purely there for presentation which means you won't get warnings when you use "unknown types" because they are not types like in MSON.

---

The example you mentioned originally appears to work as intended, I do not get any validation warnings or errors and the parameter appears to be rendered correctly.

```apib
# API Name

## GET /{?country}

+ Parameters
    + country: `uk` (enum[string], optional) - Blah blah
        + Members
            + `**`
            + `uk`
            + `it`
            + `usa`
            + `oz`

+ Response 204
```

![Screenshot 2019-07-30 at 09 59 29](https://user-images.githubusercontent.com/44164/62115693-bf996480-b2b0-11e9-9b97-c8ee4d67eb34.png)

Do you perhaps have a larger example which produces this warning (without duplicating the value in members)?

**Comment by anentropic** [comment]
Ah sorry my mistake, we have a lot of repeated instances of similar code 🤦‍♂ 

You're correct, the example I gave doesn't fail, the ones that fail are `Attributes` (i.e. POST body) and in MSON:

```apib
### Add user to country [POST]

Add a user to a country. 

+ Attributes
    + user_id: 1234 (number, required)
    + country: `uk` (enum[string], optional) - Blah blah
        + Members
            + `**`
            + `uk`
            + `it`
            + `usa`
            + `oz`
```
renders how we want 
![Screenshot 2019-07-30 at 14 42 45](https://user-images.githubusercontent.com/147840/62134436-62b1a480-b2d8-11e9-93f7-7f417ffc69e2.png)
but gives `duplicit value in enumeration` error
 

```apib
## UserCountry
- id: 534 (number, required)
- edition: `uk` (enum[string], required) - Blah blah
    + Members
        + `**`
        + `uk`
        + `it`
        + `usa`
        + `oz`
```
same, renders with sample but gives error

**Comment by kylef** [comment]
Ok in this case, it seems that as the explicit members and the in-line member are equivilent so they are treated as semantically the same and thus you get a warning about a duplicate value.

If you are trying to represent the default value of the enum as `uk` then you can add default as a type attribute:

```markdown
- edition: `uk` (enum, required, default) - Blah blah
    - uk
    - it
```

If you want the parser to use it as the example value instead of picking the first out of the list of enumeration members, then you can add the sample type attribute. This applies to the value used to represent the enumeration in JSON:


```markdown
- edition: `uk` (enum, required, sample) - Blah blah
    - it
    - uk
```

Otherwise, it can be ommitted as the value is listed in the enumeration members. You can place it as the top of the list if you want it to be preffered example value (or use sample as above).

**Comment by anentropic** [comment]
ah yes that works

I had tried this earlier
```apib
- edition: `uk` (enum, required, sample) - Blah blah
    - it
    - uk
```
but it must have been in a `Parameters` section as I got a different error like unrecognised syntax block

it is a shame there are so many same-but-different contexts in the syntax

**Comment by kylef** [comment]
> it is a shame there are so many same-but-different contexts in the syntax

Agreed, unfortunately it isn't something that we've addressed yet but it is on our roadmap. We'd like to make both parameters and headers defined via MSON, there is a proposal at https://github.com/apiaryio/api-blueprint-rfcs/pull/3 of how this would work. It would address a lot of inconsistencies such as the ones you've discovered.

Does this address all your questions?

**Comment by anentropic** [comment]
yes, thanks
